name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200

      - name: Create Classic Package
        uses: BigWigsMods/packager@master
        with:
          args: -g classic -m .pkgmeta-classic
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Create BCC Package
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc -m .pkgmeta-bcc
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
